version: '3'
services:
  dags:
    image: ghcr.io/anggutie-dev/dags:latest
    build:
      dockerfile: ./docker/dags/Dockerfile
      context: .
  airflow:
    image: ghcr.io/anggutie-dev/airflow-custom:latest
    build:
      dockerfile: ./docker/airflow/Dockerfile
      context: .